### ISSUE TITLE
Sensor naming could be improved

### ISSUE THREAD

**Issue by Bertk** [MadOne/weishaupt_modbus#2]
Thank you for the great HA integration. 

Some HA entity names for the Weishaupt_modbus integration does not refer the device & section information which might create some confusion.

I noticed also sensor `Raumfeuchte` (value: 'Unbekannt') which does not exist in _Weishaupt WEM Portal_ integration. It would be nice if this would be suppressed if it is not available. Maybe this is available in a other heat pump model. I have a WSB 6-A-RME.
<img width="699" alt="image" src="https://github.com/user-attachments/assets/719b01aa-e873-4d65-ba5b-f0355d469bf3">

_Weishaupt_modbus **Heizkreis**_
<img width="329" alt="image" src="https://github.com/user-attachments/assets/bc99f10f-e760-452b-adaf-9a320dc13d8f">

_Weishaupt WEM Portal entities_
<img width="323" alt="image" src="https://github.com/user-attachments/assets/30045131-c4dc-4f86-9f4f-e97275a5b1c7">

**Comment by MadOne** [comment]
As far is i know there are some extra devices to by in order to savely aktivate cooling (
Because for cooling the dew point has to be known) or for regulation of the heating.
I already tried to find a solution to filter out those unknown values but did not find a solution yet.
Maybe add a switch in the options to activate them.

For the entitiy naming, i tried to group them into devices.
As far is i understand you suggest to prefix the naming with the section.
Vorlauftemperatur would then be Heizkreis-Vorlauftemperatur. Did i understand you right?
I think die entity names would be too long. Especially for mobile devices.
But i understand it might be confusing if you use the values outside of the device section.

Maybe use a shortcut prefix  HK for **H**eiz**K**reis ==> HK_Vorlauftemperatur


The lightening symbol you marked is from the WEM portal integration and false there. Im i right?

**Comment by Bertk** [comment]
>As far is i know there are some extra devices to by in order to savely activate cooling (
>Because for cooling the dew point has to be known) or for regulation of the heating.
>I already tried to find a solution to filter out those unknown values but did not find a solution yet.
>Maybe add a switch in the options to activate them.

I see. A switch would be perfect.  I have radiator thermostats in every room (with humidity sensor) but no panel or floor heating.

<img width="1303" alt="image" src="https://github.com/user-attachments/assets/5d59370b-4de9-47c8-9c9d-c04d49682f16">

> Maybe use a shortcut prefix HK for HeizKreis ==> HK_Vorlauftemperatur

I would also add the device prefix eg. `WP_HK_Vorlauftemperatur`

> The lightening symbol you marked is from the WEM portal integration and false there. Im i right?

That is correct.

**Comment by MadOne** [comment]
I also thought about that. But then there would be WP_WP_Betrieb.

**Comment by Bertk** [comment]
Yes, and I would just drop the second “_WP” because searching entities for WP would find everything.

**Comment by MadOne** [comment]
Hi, 
thanks for your bug report.
There is a fork of my integration at : https://github.com/OStrama/weishaupt_modbus
I think his approach is far superor to mine. I think this integration will not be developed anymore.

**Comment by Bertk** [comment]
Hi, thank you for this information. Please consider to archive this repository to make it read-only.
(see https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories)

>Before archiving your repository, make sure you’ve changed its settings and consider closing all open issues and pull requests. You should also update your README and description to make it clear to visitors that it’s no longer possible to contribute.
>
>If you change your mind and want to unarchive your repository, click Unarchive this repository in the same place. Please note that most archived repository settings are hidden and you’ll have to unarchive the repository to change them.

**Comment by MadOne** [comment]
This integration is no longer developed, so i close the issue.
